2023-06-28 10:35:25,467 main.py [line: 21] INFO: main
2023-06-28 10:35:26,097 factory.py [line: 19] DEBUG: Not in REPL -> leaving logger event level as is.
2023-06-28 10:35:26,897 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.address`.
2023-06-28 10:35:26,907 factory.py [line: 97] DEBUG: Provider `faker.providers.address` has been localized to `en_US`.
2023-06-28 10:35:26,917 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.automotive`.
2023-06-28 10:35:26,937 factory.py [line: 97] DEBUG: Provider `faker.providers.automotive` has been localized to `en_US`.
2023-06-28 10:35:26,946 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.bank`.
2023-06-28 10:35:26,947 factory.py [line: 88] DEBUG: Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2023-06-28 10:35:26,957 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.barcode`.
2023-06-28 10:35:26,957 factory.py [line: 97] DEBUG: Provider `faker.providers.barcode` has been localized to `en_US`.
2023-06-28 10:35:26,967 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.color`.
2023-06-28 10:35:26,977 factory.py [line: 97] DEBUG: Provider `faker.providers.color` has been localized to `en_US`.
2023-06-28 10:35:26,977 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.company`.
2023-06-28 10:35:26,987 factory.py [line: 97] DEBUG: Provider `faker.providers.company` has been localized to `en_US`.
2023-06-28 10:35:26,997 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.credit_card`.
2023-06-28 10:35:26,997 factory.py [line: 97] DEBUG: Provider `faker.providers.credit_card` has been localized to `en_US`.
2023-06-28 10:35:27,007 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.currency`.
2023-06-28 10:35:27,017 factory.py [line: 97] DEBUG: Provider `faker.providers.currency` has been localized to `en_US`.
2023-06-28 10:35:27,017 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.date_time`.
2023-06-28 10:35:27,027 factory.py [line: 97] DEBUG: Provider `faker.providers.date_time` has been localized to `en_US`.
2023-06-28 10:35:27,037 factory.py [line: 109] DEBUG: Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 10:35:27,037 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.geo`.
2023-06-28 10:35:27,037 factory.py [line: 97] DEBUG: Provider `faker.providers.geo` has been localized to `en_US`.
2023-06-28 10:35:27,047 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.internet`.
2023-06-28 10:35:27,062 factory.py [line: 97] DEBUG: Provider `faker.providers.internet` has been localized to `en_US`.
2023-06-28 10:35:27,067 factory.py [line: 109] DEBUG: Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 10:35:27,067 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.job`.
2023-06-28 10:35:27,077 factory.py [line: 97] DEBUG: Provider `faker.providers.job` has been localized to `en_US`.
2023-06-28 10:35:27,077 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.lorem`.
2023-06-28 10:35:27,092 factory.py [line: 97] DEBUG: Provider `faker.providers.lorem` has been localized to `en_US`.
2023-06-28 10:35:27,097 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.misc`.
2023-06-28 10:35:27,097 factory.py [line: 97] DEBUG: Provider `faker.providers.misc` has been localized to `en_US`.
2023-06-28 10:35:27,107 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.person`.
2023-06-28 10:35:27,127 factory.py [line: 97] DEBUG: Provider `faker.providers.person` has been localized to `en_US`.
2023-06-28 10:35:27,137 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.phone_number`.
2023-06-28 10:35:27,157 factory.py [line: 97] DEBUG: Provider `faker.providers.phone_number` has been localized to `en_US`.
2023-06-28 10:35:27,162 factory.py [line: 109] DEBUG: Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 10:35:27,162 factory.py [line: 109] DEBUG: Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 10:35:27,162 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.ssn`.
2023-06-28 10:35:27,177 factory.py [line: 97] DEBUG: Provider `faker.providers.ssn` has been localized to `en_US`.
2023-06-28 10:35:27,188 factory.py [line: 109] DEBUG: Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 10:35:30,297 conftest.py [line: 125] INFO: 用例总数: 3
2023-06-28 10:35:30,297 conftest.py [line: 126] INFO: 异常用例数: 0
2023-06-28 10:35:30,297 conftest.py [line: 127] INFO: 失败用例数: 0
2023-06-28 10:35:30,297 conftest.py [line: 128] WARNING: 跳过用例数: 0
2023-06-28 10:35:30,297 conftest.py [line: 129] INFO: 用例执行时长: 3.47 s
2023-06-28 10:35:30,297 conftest.py [line: 133] INFO: 用例成功率: 100.00 %
2023-06-28 11:04:55,213 globalVars.py [line: 150] ERROR: 项目运行全局变值不存在，获取失败：>>> key=a
2023-06-28 11:05:04,253 globalVars.py [line: 150] ERROR: 项目运行全局变值不存在，获取失败：>>> key=a
2023-06-28 11:05:28,593 globalVars.py [line: 151] ERROR: 项目运行全局变值不存在，获取失败：>>> key=a
2023-06-28 11:07:36,263 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>.\APIAutoTestModel\common\sysFile\project_var.json
2023-06-28 11:22:20,817 main.py [line: 21] INFO: main
2023-06-28 11:22:21,433 factory.py [line: 19] DEBUG: Not in REPL -> leaving logger event level as is.
2023-06-28 11:22:24,682 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.json
2023-06-28 11:22:24,882 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.json
2023-06-28 11:22:25,262 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.json
2023-06-28 11:22:25,553 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.json
2023-06-28 11:22:25,702 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.json
2023-06-28 11:22:25,842 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.json
2023-06-28 11:22:27,812 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.json
2023-06-28 11:25:29,952 main.py [line: 21] INFO: main
2023-06-28 11:25:30,563 factory.py [line: 19] DEBUG: Not in REPL -> leaving logger event level as is.
2023-06-28 11:25:33,602 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:33,972 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:34,182 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:34,332 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:34,432 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:34,702 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:36,303 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:54,132 main.py [line: 21] INFO: main
2023-06-28 11:25:54,782 factory.py [line: 19] DEBUG: Not in REPL -> leaving logger event level as is.
2023-06-28 11:25:57,692 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:57,948 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:58,233 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:58,466 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:58,753 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:25:58,783 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:26:00,453 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:26:54,517 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>sysFile\project_var.txt
2023-06-28 11:27:44,860 fileOperation.py [line: 52] ERROR: 文件不存在, 获取数据失败: >>>.\sysFile\project_var.txt
2023-06-28 12:20:58,527 main.py [line: 21] INFO: main
2023-06-28 12:20:59,167 factory.py [line: 19] DEBUG: Not in REPL -> leaving logger event level as is.
2023-06-28 12:20:59,917 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.address`.
2023-06-28 12:20:59,948 factory.py [line: 97] DEBUG: Provider `faker.providers.address` has been localized to `en_US`.
2023-06-28 12:20:59,948 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.automotive`.
2023-06-28 12:20:59,964 factory.py [line: 97] DEBUG: Provider `faker.providers.automotive` has been localized to `en_US`.
2023-06-28 12:20:59,964 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.bank`.
2023-06-28 12:20:59,979 factory.py [line: 88] DEBUG: Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2023-06-28 12:20:59,979 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.barcode`.
2023-06-28 12:20:59,995 factory.py [line: 97] DEBUG: Provider `faker.providers.barcode` has been localized to `en_US`.
2023-06-28 12:20:59,995 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.color`.
2023-06-28 12:20:59,995 factory.py [line: 97] DEBUG: Provider `faker.providers.color` has been localized to `en_US`.
2023-06-28 12:21:00,011 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.company`.
2023-06-28 12:21:00,026 factory.py [line: 97] DEBUG: Provider `faker.providers.company` has been localized to `en_US`.
2023-06-28 12:21:00,026 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.credit_card`.
2023-06-28 12:21:00,026 factory.py [line: 97] DEBUG: Provider `faker.providers.credit_card` has been localized to `en_US`.
2023-06-28 12:21:00,026 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.currency`.
2023-06-28 12:21:00,042 factory.py [line: 97] DEBUG: Provider `faker.providers.currency` has been localized to `en_US`.
2023-06-28 12:21:00,042 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.date_time`.
2023-06-28 12:21:00,058 factory.py [line: 97] DEBUG: Provider `faker.providers.date_time` has been localized to `en_US`.
2023-06-28 12:21:00,058 factory.py [line: 109] DEBUG: Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 12:21:00,058 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.geo`.
2023-06-28 12:21:00,058 factory.py [line: 97] DEBUG: Provider `faker.providers.geo` has been localized to `en_US`.
2023-06-28 12:21:00,073 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.internet`.
2023-06-28 12:21:00,089 factory.py [line: 97] DEBUG: Provider `faker.providers.internet` has been localized to `en_US`.
2023-06-28 12:21:00,089 factory.py [line: 109] DEBUG: Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 12:21:00,089 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.job`.
2023-06-28 12:21:00,104 factory.py [line: 97] DEBUG: Provider `faker.providers.job` has been localized to `en_US`.
2023-06-28 12:21:00,104 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.lorem`.
2023-06-28 12:21:00,104 factory.py [line: 97] DEBUG: Provider `faker.providers.lorem` has been localized to `en_US`.
2023-06-28 12:21:00,120 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.misc`.
2023-06-28 12:21:00,120 factory.py [line: 97] DEBUG: Provider `faker.providers.misc` has been localized to `en_US`.
2023-06-28 12:21:00,120 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.person`.
2023-06-28 12:21:00,151 factory.py [line: 97] DEBUG: Provider `faker.providers.person` has been localized to `en_US`.
2023-06-28 12:21:00,151 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.phone_number`.
2023-06-28 12:21:00,167 factory.py [line: 97] DEBUG: Provider `faker.providers.phone_number` has been localized to `en_US`.
2023-06-28 12:21:00,183 factory.py [line: 109] DEBUG: Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 12:21:00,183 factory.py [line: 109] DEBUG: Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 12:21:00,183 factory.py [line: 78] DEBUG: Looking for locale `en_US` in provider `faker.providers.ssn`.
2023-06-28 12:21:00,198 factory.py [line: 97] DEBUG: Provider `faker.providers.ssn` has been localized to `en_US`.
2023-06-28 12:21:00,198 factory.py [line: 109] DEBUG: Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2023-06-28 12:21:03,030 conftest.py [line: 125] INFO: 用例总数: 3
2023-06-28 12:21:03,030 conftest.py [line: 126] INFO: 异常用例数: 0
2023-06-28 12:21:03,030 conftest.py [line: 127] INFO: 失败用例数: 0
2023-06-28 12:21:03,030 conftest.py [line: 128] WARNING: 跳过用例数: 0
2023-06-28 12:21:03,030 conftest.py [line: 129] INFO: 用例执行时长: 3.16 s
2023-06-28 12:21:03,030 conftest.py [line: 133] INFO: 用例成功率: 100.00 %
